name       : modemmanager-qt
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/modemmanager-qt-5.32.0.tar.xz : cdcba37196adddb8298c3fdbeb9da735bd186a92226460ed2cca1339038e9e7b
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
