name       : modemmanager-qt
version    : 5.63.0
release    : 29
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.63/modemmanager-qt-5.63.0.tar.xz : 4d0153d89be703662c11839adc5f4883df32ecc9b4781b0a20c07bcfc2c1657b
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
