name       : modemmanager-qt
version    : 5.53.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/modemmanager-qt-5.53.0.tar.xz : b74d449bcdedaaedbed85c6a4b3989c53bb27f2833b90b96a93a88691090fbd1
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
