name       : modemmanager-qt
version    : 5.60.0
release    : 26
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.60/modemmanager-qt-5.60.0.tar.xz : 461b99099376d1210dad7867627c67b2a64af908a4fca0aeed75fc36059cad4e
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
