name       : modemmanager-qt
version    : 5.90.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.90/modemmanager-qt-5.90.0.tar.xz : 09987b2625de29626de27c30e4b589f3962596b80f1114afce836e4ecbdbd422
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.library
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
optimize   : lto
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
