name       : modemmanager-qt
version    : 5.43.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/modemmanager-qt-5.43.0.tar.xz : dc502277001cdf65fe5118780e9c8cb3c568af54c387d7c2b0904a438053089a
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
