name       : modemmanager-qt
version    : 5.36.0
release    : 3
source     :
    - https://download.kde.org/stable/frameworks/5.36/modemmanager-qt-5.36.0.tar.xz : 0e806c01add2c02492e8fcdfff718cedcf3e1cf25e661f6d930e3adec9192f51
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
