name       : modemmanager-qt
version    : 5.56.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.56/modemmanager-qt-5.56.0.tar.xz : 6cd1490efcfeddd64cc536889b9e675077d76cbce6fcebb0a216c9b8bc379df7
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
