name       : modemmanager-qt
version    : 5.50.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/modemmanager-qt-5.50.0.tar.xz : faeb447d739fec0ae0042065a0ab52f4437ffb54f1c87c78941b5f06e3a8f1f0
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
