name       : modemmanager-qt
version    : 5.59.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/modemmanager-qt-5.59.0.tar.xz : b64034487330286f37ee792256b00b3ff16ee4ce3965a1c3eb93453e77a20a37
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
