name       : modemmanager-qt
version    : 5.40.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/modemmanager-qt-5.40.0.tar.xz : d2d97f7efa6a2728892111b72336ab686e742ab9eccbb2779aea23463cbb1244
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
