name       : modemmanager-qt
version    : 5.39.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.39/modemmanager-qt-5.39.0.tar.xz : 67fe53c0069dfafacfdbee167db762c49f9dcb97c75b29f0724cfa1340b8ba3d
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
