name       : modemmanager-qt
version    : 5.65.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.65/modemmanager-qt-5.65.0.tar.xz : 21cd64acbe50d402ea5c3636e628acbc8c73ee32021a6e184c449380216380c2
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
