name       : modemmanager-qt
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/modemmanager-qt-5.35.0.tar.xz : a155fc74ffe4262c7866ce3a77f7370255e35b5a3d0b463681883042007b10f0
license    : LGPL-2.1
component  : desktop.library
summary    : Qt wrapper for ModemManager DBus API
description: |
    ModemManagerQt provides access to all ModemManager features exposed on DBus. It allows you to manage modem devices and access to information available for your modem devices, like signal, location and messages.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
